// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQvo0IKfgfv_pPyIZuQC_VqPHrL43ojc',
    appId: '1:390501147977:web:b2a9ecd6d6fcd85f9d6698',
    messagingSenderId: '390501147977',
    projectId: 'all-authetication',
    authDomain: 'all-authetication.firebaseapp.com',
    storageBucket: 'all-authetication.firebasestorage.app',
    measurementId: 'G-ND59HTS5JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnP6zQKcJDTDhuYrAW4c_tATK5r1kd2_Y',
    appId: '1:390501147977:android:c811efb86775c7539d6698',
    messagingSenderId: '390501147977',
    projectId: 'all-authetication',
    storageBucket: 'all-authetication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESvNCEPwjr4u2s3Auhnr00PJgJFsn5Kg',
    appId: '1:390501147977:ios:b31b11760ca7c63b9d6698',
    messagingSenderId: '390501147977',
    projectId: 'all-authetication',
    storageBucket: 'all-authetication.firebasestorage.app',
    iosBundleId: 'com.example.allAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESvNCEPwjr4u2s3Auhnr00PJgJFsn5Kg',
    appId: '1:390501147977:ios:b31b11760ca7c63b9d6698',
    messagingSenderId: '390501147977',
    projectId: 'all-authetication',
    storageBucket: 'all-authetication.firebasestorage.app',
    iosBundleId: 'com.example.allAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTQvo0IKfgfv_pPyIZuQC_VqPHrL43ojc',
    appId: '1:390501147977:web:85d5fe65fc69bf699d6698',
    messagingSenderId: '390501147977',
    projectId: 'all-authetication',
    authDomain: 'all-authetication.firebaseapp.com',
    storageBucket: 'all-authetication.firebasestorage.app',
    measurementId: 'G-NVDMR0RY4V',
  );
}
